service: notification-service

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  iamRoleStatements:
  - ${file(iam/SendMailIAM.yml):SendMailIAM}
  

functions:
  sendMail:
    handler: src/handlers/sendMail.handler

custom:
  bundle:
    linting: false
