service: auction-service

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
  region: eu-central-1
  iamRoleStatements:
    - ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM}

resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionsTable.yaml):AuctionsTable}
  
functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction
          cors: true
          integration: lambda
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: arn:aws:cognito-idp:${aws:region}:${aws:accountId}:userpool/eu-central-1_D8nQnDQ8y
            claims:
              - email

  getAuctions:
    handler: src/handlers/getAuctions.handler
    events:
      - http:
          method: GET
          path: /auctions
          integration: lambda
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: arn:aws:cognito-idp:${aws:region}:${aws:accountId}:userpool/eu-central-1_D8nQnDQ8y
            claims:
              - email
  getAuctionById:
    handler: src/handlers/getAuctionById.handler
    events:
      - http:
          method: GET
          path: /auctions/{id}
          integration: lambda
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: arn:aws:cognito-idp:${aws:region}:${aws:accountId}:userpool/eu-central-1_D8nQnDQ8y
            claims:
              - email
  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - http:
          method: PATCH
          path: /auctions/{id}/bid
          integration: lambda
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: arn:aws:cognito-idp:${aws:region}:${aws:accountId}:userpool/eu-central-1_D8nQnDQ8y
            claims:
              - email
  processAuction:
    handler: src/handlers/processAuction.handler
    # events:
    #   - schedule: rate(1 minute)

custom:
  bundle:
    linting: false
  AuctionsTable:
    name: !Ref AuctionsTable
    arn: !GetAtt AuctionsTable.Arn


